#!/bin/bash
set -e
cat > /var/www/vpn-panel/assets/style.css <<'EOF'
:root{--bg:#07101c;--card:#0c1730;--text:#e5eefc;--muted:#8ea3c8;--line:rgba(111,140,191,.18);--ok:#22c55e;--warn:#f59e0b;--bad:#ef4444;--shadow:0 20px 50px rgba(0,0,0,.35)}
*{box-sizing:border-box}body{margin:0;color:var(--text);font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;background:radial-gradient(1000px 600px at 10% 0%, rgba(34,199,255,.14), transparent 55%),radial-gradient(900px 540px at 90% 10%, rgba(71,118,255,.14), transparent 60%),linear-gradient(180deg,#050b15,var(--bg))}
a{text-decoration:none;color:inherit}.container{max-width:1280px;margin:0 auto;padding:18px}.card{background:linear-gradient(180deg,rgba(11,24,52,.88),rgba(7,15,31,.85));border:1px solid var(--line);border-radius:22px;box-shadow:var(--shadow)}.header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid var(--line);flex-wrap:wrap}.brand{display:flex;align-items:center;gap:12px}.logo{width:48px;height:48px;border-radius:16px;background:linear-gradient(145deg,#17d0ff,#284cff)}.h1{font-size:20px;font-weight:900}.sub{font-size:13px;color:var(--muted)}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:1px solid rgba(34,199,255,.20);background:linear-gradient(180deg,rgba(34,199,255,.12),rgba(71,118,255,.10));color:var(--text);padding:11px 14px;border-radius:14px;font-weight:800;font-size:13px;display:inline-block;cursor:pointer}.btn.gray{border-color:rgba(156,163,175,.20);background:rgba(148,163,184,.10)}.btn.red{border-color:rgba(239,68,68,.20);background:rgba(239,68,68,.12)}.grid{display:grid;grid-template-columns:1fr;gap:16px;padding:18px}.tablewrap{overflow:auto;border-radius:18px;border:1px solid var(--line)}table{width:100%;border-collapse:collapse;background:rgba(4,10,22,.55)}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#b8ddff}.input,select,textarea{width:100%;padding:12px 14px;border-radius:14px;border:1px solid var(--line);background:rgba(2,8,20,.55);color:var(--text);outline:none}.notice,.err{padding:14px 16px;border-radius:16px;border:1px solid var(--line)}.notice{background:rgba(34,199,255,.08);color:#d8f7ff}.err{background:rgba(239,68,68,.10);color:#ffe0e0}.statgrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(min-width:980px){.statgrid{grid-template-columns:repeat(4,1fr)}}.stat{background:linear-gradient(180deg,rgba(10,23,49,.95),rgba(5,12,28,.95));border:1px solid var(--line);border-radius:18px;padding:16px}.stat .k{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.stat .v{margin-top:8px;font-size:28px;font-weight:900}.badge{display:inline-flex;align-items:center;gap:8px;padding:6px 10px;border-radius:999px;font-size:12px;font-weight:900;border:1px solid transparent}.b-ok{background:rgba(34,197,94,.12);color:#c6ffd8;border-color:rgba(34,197,94,.25)}.b-bad{background:rgba(239,68,68,.12);color:#ffd1d1;border-color:rgba(239,68,68,.25)}.b-warn{background:rgba(245,158,11,.12);color:#ffe3ad;border-color:rgba(245,158,11,.25)}.logbox{height:320px;overflow:auto;background:rgba(2,7,19,.7);border:1px solid var(--line);border-radius:18px;padding:14px;white-space:pre-wrap}
EOF
cat > /var/www/vpn-panel/index.php <<'EOF'
<?php header("Location: /admin/login.php"); exit; ?>
EOF
cat > /var/www/vpn-panel/admin/config.php <<'EOF'
<?php
session_start();
date_default_timezone_set('Asia/Manila');
define('DB_HOST','localhost'); define('DB_NAME','vpn_panel'); define('DB_USER','tamj'); define('DB_PASS','StrongPass123'); define('API_KEY','SERVER1_SECRET_KEY'); define('APP_TOKEN','TAMJ_APP_2026_SECRET'); define('ONLINE_SECONDS',300);
$pdo = new PDO("mysql:host=".DB_HOST.";dbname=".DB_NAME.";charset=utf8mb4", DB_USER, DB_PASS, [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
function h($s){ return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function require_login(){ if(!isset($_SESSION['admin_id'])){ header("Location: login.php"); exit; } }
function enc_secret($plain){ $iv=substr(hash('sha256', APP_TOKEN),0,16); return openssl_encrypt((string)$plain,'aes-256-cbc',APP_TOKEN,0,$iv) ?: ''; }
function dec_secret($cipher){ $iv=substr(hash('sha256', APP_TOKEN),0,16); return openssl_decrypt((string)$cipher,'aes-256-cbc',APP_TOKEN,0,$iv) ?: ''; }
function stat_badge($status){ if($status==='ONLINE') return '<span class="badge b-ok">ONLINE</span>'; if($status==='INSTALLING' || $status==='QUEUED') return '<span class="badge b-warn">'.h($status).'</span>'; if($status==='OFFLINE' || $status==='ERROR') return '<span class="badge b-bad">'.h($status).'</span>'; return '<span class="badge b-warn">'.h($status).'</span>'; }
EOF
cat > /var/www/vpn-panel/admin/login.php <<'EOF'
<?php require __DIR__."/config.php"; if(isset($_SESSION['admin_id'])){ header("Location: index.php"); exit; } $err=''; if($_SERVER['REQUEST_METHOD']==='POST'){ $u=trim($_POST['username']??''); $p=(string)($_POST['password']??''); $st=$pdo->prepare("SELECT * FROM admins WHERE username=? AND status=1 LIMIT 1"); $st->execute([$u]); $a=$st->fetch(); if($a && password_verify($p,$a['password'])){ $_SESSION['admin_id']=(int)$a['id']; $_SESSION['admin_username']=$a['username']; $_SESSION['admin_role']=$a['role']; header("Location: index.php"); exit; } $err='Invalid username or password'; } ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="../assets/style.css"><title>Login</title></head><body><div class="container"><div class="card" style="max-width:520px;margin:60px auto"><div class="header"><div class="brand"><div class="logo"></div><div><div class="h1">VPN Panel</div><div class="sub">TAMJ V3.6 Final</div></div></div></div><div class="grid"><?php if($err): ?><div class="err"><?=h($err)?></div><?php endif; ?><form method="post"><label>Username</label><input class="input" name="username" required><div style="height:10px"></div><label>Password</label><input class="input" type="password" name="password" required><div style="height:14px"></div><button class="btn" style="width:100%">Login</button></form><div class="small">Default admin: <b>admin</b> / <b>admin123</b></div></div></div></div></body></html>
EOF
